version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: db_studydesa
    ports:
      - "3306:3306"
  
  nodejs:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql